
export const produits= [
  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "Toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 1,
  },

  {
    "type": "Meuble",
    "détails": "Table déco",
    "nom": "Table déco",
    "dimensions": "58x36cm",
    "matière": "Bois",
    "prix": "800 Dhs",
    "cadré": "Non",
    "état": "2ème main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/table-simolazrak1.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 2,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 3,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 4,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 5,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 6,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 7,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 8,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 9,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 10,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 11,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 12,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 13,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 14,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 15,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 16,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 17,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 18,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 19,
  },

  {
    "type": "Tableau",
    "détails": "Benjkan Salah/100x100cm/Toile",
    "nom": "Benjkan Salah",
    "dimensions": "100x100cm",
    "matière": "toile",
    "prix": "10.000 Dhs",
    "cadré": "Non",
    "état": "2ème Main",
    "Contact": "06-58",
    "thumbnail": "../imagesTableaux/N385.jpg", //On met .. pour pouvoir accéder à l'image partout, même dans le component FicheProduit
    "image-fiche1": "",
    "image-fiche2": "",
    "code": "Ref: 385",
    "id": 20,
  },
]